Updated Documentation to Reflect New Architecture
yokozach/The-Mechanical-Forest pull request #142
Opened 2023-10-07 03:49 UTC by GenoImel

**Changes:**
Updated the `CodingStandards.md` documentation including:
      - Added documentation for `State Machines`.
      - Updated inheritance standards for `IMonoSystems` and other core `interfaces` such that the inheritance happens at the specific `interface` rather than in the `MonoBehaviour` companion scripts.
      - Expanded documentation for file/folder organization for `Assets`.
      - Added concluding paragraphs to each section, and a document summary at the end.
- Updated the `CoreArchitecture.md` documentation including:
      - Overview for the `ApplicationManager`.
      - In-depth documentation for `Message Bus` core components including `IMessage`, `MessageListener`, and `MessageManager`.
      - Deep dive on `MonoSystems` including documentation for `IMonoSystems` and `MonoSystemsManager`.
      - Detailed descriptions of `StateMachines` including documentation for `IState`, `IFiniteState`, `IStateMachine`, `BaseStateMachine`, `StateChangedMessage`, and `StateMachineManager`.
      - Overview for the AkashicApplicationManager`.
      
**For More Info See:**
closes #140

2023-10-07 03:51 UTC, yokozach approved these changes

2023-10-09 17:10 UTC, jckrebs requested changes
Found a few typos.

2023-10-09 23:09 UTC, yokozach approved these changes

2023-10-10 07:45 UTC, jckrebs approved these changes

2023-10-10 10:55 UTC, merged