Create serializer classes for inventory and items
yokozach/The-Mechanical-Forest pull request #174
Opened 2023-10-23 19:04 UTC by Sbrebbaz

Created Serializers for InventoryItem, Accessory, Consumable, Relic
Created PartyInventory for managing all the Inventory items
Added PartyInventory to SaveSlot class

Added IIinventoryMonoSystem base functions for handling inventory creation and retrieving
Base inventory creation in SaveFile reading

2023-10-24 03:03 UTC, GenoImel commented on Assets/Scripts/Runtime/Controllers/SaveMenu/SaveSlot.cs
> +			var saveFile = new SaveFile(saveSlotNameText.text, partyMembers, new PartyInventory(new List<InventoryItem>()));
For code readability purposes, it might be good to break this line apart like so:

```csharp
			var saveFile = new SaveFile(
                saveSlotNameText.text, 
                partyMembers, 
                new PartyInventory(new List<InventoryItem>())
                );
```

2023-10-24 03:10 UTC, GenoImel commented on Assets/Scripts/Runtime/MonoSystems/Inventory/IInventoryMonoSystem.cs
> +		/// Returns the party inventory.
Sometimes its a good idea to make our XML documentation a bit fancy by using things like `<see cref="SomeClass"/>` or `<paramref name="someParameter""/>`. You could do that here by doing something like:

```csharp
/// <summary>
/// Returns the current <see cref="PartyInventory"/>.
/// </summary>
public PartyInventory GetInventory();
```

Doing this will create clickable links that can take people to the class in question and more!

![image](https://github.com/yokozach/The-Mechanical-Forest/assets/99087864/18179ff7-7e78-4176-964b-ebf6d66b7a8e)

You don't have to make this change, this is just more or less a tip for fancier XML documentation. 😄

2023-10-24 03:12 UTC, GenoImel commented on Assets/Scripts/Runtime/MonoSystems/Inventory/InventoryMonoSystem.cs
> +		private PartyInventory inventory;
Could be good to name this `currentInventory`, or even just `partyInventory`... but now I'm in nitpick mode and that's more or less developer preference. 🤔

2023-10-24 03:16 UTC, GenoImel commented on Assets/Scripts/Runtime/Serializers/AccessoryItem.cs
> +﻿using Newtonsoft.Json;
Our folder for our json serializer classes is getting a little cluttered. It might be good to consider organizing these into subfolders based on category at some point. 🤔

2023-10-24 03:18 UTC, GenoImel commented on Assets/Scripts/Runtime/Serializers/PartyInventory.cs
> +				return Items.OfType<RelicItem>().ToList();
When I look at this in Jetbrains Rider, it suggests changing these to autoproperties like so:

```csharp
		[JsonIgnore]
		public List<RelicItem> Relics => Items.OfType<RelicItem>().ToList();

		[JsonIgnore]
		public List<ConsumableItem> Consumables => Items.OfType<ConsumableItem>().ToList();

		[JsonIgnore]
		public List<AccessoryItem> Accessories => Items.OfType<AccessoryItem>().ToList();
```

This would help for overall readability, and keep the class nice and compact.

2023-10-24 03:29 UTC, GenoImel requested changes
Some of my changes (like for enhanced XML documentation) is definitely within the realm of nitpick mode. Others are more related to code readability or codebase organization.

Otherwise this looks really good. Also, thanks for going ahead and modifying the `SaveMonoSystem` and related scripts during this PR. 😄

2023-10-24 16:40 UTC, GenoImel approved these changes
Looks good. Thanks for reorganizing the Serializers folder, it looks way less chaotic now. 😄

2023-10-25 18:25 UTC, yokozach approved these changes

2023-10-25 18:27 UTC, merged