179 create resourcemonosystem
yokozach/The-Mechanical-Forest pull request #193
Opened 2023-11-12 21:53 UTC by Sbrebbaz

Created `ResourceMonoSystem` and `IResourceMonoSystem` 
Updated `Gamemanager` to include the `ResourceMonoSystem` 
Created Database resource SO + instances for current items
Created message for `OnResourceLoadedMessage` (Currently unused)

Closes #179

2023-11-12 22:43 UTC, GenoImel requested changes
I left some suggestions for minor changes. Good job on this! 😄 

For anyone else who is interested, after some discussion Srebbaz and I decided that we'll eventually want to move over to using the official Unity Asset Bundles package to optimize loading and management of our game's resources. But this works alright for now.

2023-11-12 22:43 UTC, GenoImel commented on Assets/ScriptableObjects/Database/AccessoryDatabaseData.cs
> +	internal sealed class AccessoryDatabaseData : ScriptableObject
In this case, we can probably omit the word "Data" from the scripts for these SOs, as well as the SO instances themselves. "Database" alone is likely sufficient and avoids redundancy.

2023-11-12 22:43 UTC, GenoImel commented on Assets/Scripts/Runtime/MonoSystems/Resource/ResourceMonoSystem.cs
> +		private ICollection<ConsumableData> consumables = new List<ConsumableData>();
Since our SOs that we have injected via the editor already contain the list of SOs needed for the game, we can probably avoid copying them to a separate list entirely, and grab them from the SO directly. 🤔

2023-11-12 22:43 UTC, GenoImel commented on Assets/Scripts/Runtime/MonoSystems/Resource/ResourceMonoSystem.cs
> +using Akashic.Core;
I think we have some unused namespaces here.

2023-11-13 21:30 UTC, GenoImel approved these changes
Looks good. Nice work. 😄

2023-11-14 13:07 UTC, yokozach approved these changes

2023-11-14 17:56 UTC, merged